### ISSUE TITLE
Cluster doesn't update from upstream any more?

### ISSUE THREAD

**Issue by mohe2015** [RubenKelevra/pacman.store#19]
It seems like the most recent packages aren't available on the cluster yet. Did it crash or so?

**Comment by RubenKelevra** [comment]
Hey @mohe2015,

Thanks for the report!

I ran into consistency issues with the garbage collector, ticket is here:

https://github.com/ipfs/ipfs-cluster/issues/1067#issue-599234265

The setup should be back operational in the next 24h.

Anyway, I'm not sure how to announce such stuff in the future. Any recommendations? 🤔


Best regards

Ruben

**Comment by mohe2015** [comment]
Thanks for the response. I'm fine if it takes longer, I just wanted to know whether you were aware of the issue. You could probably just open an issue here as most cluster followers are probably watching this repo and I don't know any better place.

**Comment by RubenKelevra** [comment]
I still feel like pacman should have a look at the `lastupdate` file and warn when it's older than like 24h or so... or even skip the mirror.

**Comment by mohe2015** [comment]
Yeah, I just realized that it didn't update after a few days. Have fun opening an issue upstream :D

**Comment by RubenKelevra** [comment]
> Yeah, I just realized that it didn't update after a few days. Have fun opening an issue upstream :D

It's kind of sad...

**Comment by RubenKelevra** [comment]
Short update: The provider is still running a storage optimization task on the (virtual) machine... running for 6h and 30m now. Had to run it, the IO-performance was extremly crappy.

So I guess it will take a bit longer until it's up and running again ;)

**Comment by mohe2015** [comment]
Yeah, it's totally fine (at least for me). I really appreciate you pushing forward in this direction and it was expected that issues would arise. It also seems like your experiments improve ipfs or at least make them aware of problems.

**Comment by RubenKelevra** [comment]
@mohe2015 well, I hit several bugs :D But they was great dealing with all of them!

The next cluster release will get non-recursive pins (=direct pins). This allows me to pin the folders to the cluster, and not only the files itself (pinning the folder structure recursively is extremely I/O and memory-intensive).

This should speed up the folder lookups since they don't have to be served by the one server which adds the updates to ipfs.

**Comment by RubenKelevra** [comment]
While the harddisk performance of the server is still not really top notch (I had the provider optimize it two time - dunno what's going on) I started the import.

This part of the drive seems to be fine.

**Comment by RubenKelevra** [comment]
@mohe2015 initial import is done and update will run shortly :)

You need the 0.5.0 go-ipfs client to access it since I moved in the process to use just CIDv1.

**Comment by RubenKelevra** [comment]
Damn, I found a bug in my script which leads to consistency issues of the cluster under some circumstances.

Have to reimport the cluster (just metadata) but it will take some hours.

Should be up and running in like 6 hours again.

**Comment by RubenKelevra** [comment]
Everything back to normal operation.
