### ISSUE TITLE
import stuck?

### ISSUE THREAD

**Issue by rpodgorny** [RubenKelevra/pacman.store#24]
hi, for the last three (or so) days there has been no updates for my system - which seems pretty unusual in the arch land. isn't the ipfs importer stuck?

thanks.

**Comment by rpodgorny** [comment]
on another machine which has not been updated for a while:

```
...
:: Proceed with download? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'haskell-unordered-containers-0.2.11.0-2-x86_64.pkg.tar.zst' from 127.0.0.1:8080 : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed retrieving file 'haskell-aeson-1.5.2.0-4-x86_64.pkg.tar.zst' from 127.0.0.1:8080 : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed retrieving file 'haskell-aeson-pretty-0.8.8-49-x86_64.pkg.tar.zst' from 127.0.0.1:8080 : The requested URL returned error: 404
warning: failed to retrieve some files
...
```

so it seems like only the db files are not being updated?

**Comment by RubenKelevra** [comment]
Thank you for the report. The ipfs-cluster service run into database issues and which resulted in partly imports of the diffs.

I'm working on the issue and also updated the status page to reflect that.

I apologize for the inconvenience.

**Comment by RubenKelevra** [comment]
Alright. I decided to rethink my approach and rewrote my sync script.

I create a new cluster-instance, the readme is updated.

The new cluster has a different URL, for various reasons, main one was poor performance with a lot of subfolders.

https://github.com/RubenKelevra/pacman.store#use-the-pkg-cache-with-pacman
