### ISSUE TITLE
mirror down?

### ISSUE THREAD

**Issue by rpodgorny** [RubenKelevra/pacman.store#35]
error: failed retrieving file 'core.db' from x86-64.archlinux.pkg.pacman.store.ipns.localhost:8080 : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds

...on all my (geographically distributed) machines. this is probably not an issue on my side. can you please check?

thanks!

**Comment by teknomunk** [comment]
I cannot confirm on any of my machines.

**Comment by rpodgorny** [comment]
interesting! i've tried to restart ipfs daemon on one of the machines and it fixed the issue. i'll investigate the other machines. ...so most likely a problem on my side after all. sorry for the noise.

**Comment by teknomunk** [comment]
No problem. If you want me to run experiments on my side, just ask and I'll get the results to you as soon as I am able.
