### ISSUE TITLE
DNSLink uses IPNS and not IPFS

### ISSUE THREAD

**Issue by FireMasterK** [RubenKelevra/pacman.store#38]
Hi there,

Your current setup uses `IPNS`, which is painfully slow in many areas. I would suggest you use an `IPFS` address instead of an `IPNS` one for performance reasons.

This would require modifying your `txt` record every time you update the repo but would drastically reduce the resolution times.

Thanks!

**Comment by whs** [comment]
I wrote a quick tool to resolve ipns address and update record so we can test this out: http://ipfs.io/ipns/x86-64-archlinux-pkg-pacman-store.cupco.de

(Use at your own risk as I don't have monitoring setup that the resolver still works, although I moved my mirrorlist to mine now)

**Comment by rpodgorny** [comment]
just my 2cents: using pubsub for ipns made my ipns lookups much faster.

**Comment by RubenKelevra** [comment]
Well, it's recommended to use pubsub. There should be no noticeable delay in resolving this way. :)
