### ISSUE TITLE
ipv6 connection problem?

### ISSUE THREAD

**Issue by rpodgorny** [RubenKelevra/pacman.store#51]
hi, i'm on a ipv6-only network and since some long time already i'm unable to use ipfs pacman store...

```
>ipfs --api /ip4/127.0.0.1/tcp/5001 resolve /ipns/x86-64.archlinux.pkg.pacman.store
/ipfs/bafybeidnlmimurjtvwhsji3xwbzjvylgw6kvhf3cclvfyfflvgvvxhdxau

> ipfs --api /ip4/127.0.0.1/tcp/5001 dht findprovs /ipfs/bafybeidnlmimurjtvwhsji3xwbzjvylgw6kvhf3cclvfyfflvgvvxhdxau
QmZJznS5TWZiea2zdV63qJzYkz6P5HBhPksojxhrfNximP

> ipfs --api /ip4/127.0.0.1/tcp/5001 swarm connect /ipfs/QmZJznS5TWZiea2zdV63qJzYkz6P5HBhPksojxhrfNximP
Error: connect QmZJznS5TWZiea2zdV63qJzYkz6P5HBhPksojxhrfNximP failure: failed to dial QmZJznS5TWZiea2zdV63qJzYkz6P5HBhPksojxhrfNximP: all dials failed                                         
  * [/ip6/::1/udp/4001/quic] CRYPTO_ERROR (0x12a): peer IDs don't match                                                                                                                        
  * [/ip6/2600:8803:e600:18c:e445:edff:fe20:38d3/tcp/4001] dial tcp6 [::]:4001->[2600:8803:e600:18c:e445:edff:fe20:38d3]:4001: i/o timeout
  * [/ip6/fd2c:853:d11f:0:e445:edff:fe20:38d3/tcp/4001] dial tcp6 [::]:4001->[fd2c:853:d11f:0:e445:edff:fe20:38d3]:4001: i/o timeout
  * [/ip6/fd2c:853:d11f:0:e445:edff:fe20:38d3/udp/4001/quic] NO_ERROR: Handshake did not complete in time
  * [/ip6/2600:8803:e600:18c:e445:edff:fe20:38d3/udp/4001/quic] NO_ERROR: Handshake did not complete in time

> ping 2600:8803:e600:18c:e445:edff:fe20:38d3
PING 2600:8803:e600:18c:e445:edff:fe20:38d3(2600:8803:e600:18c:e445:edff:fe20:38d3) 56 data bytes
^C
--- 2600:8803:e600:18c:e445:edff:fe20:38d3 ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9115ms
```

**Comment by RubenKelevra** [comment]
@rpodgorny Hey thanks for the report. Note that I removed the QUIC protocol from the server. I have trouble with performance with it with go-ipfs 0.8 but haven't had time to investigate yet.

So the failure to connect via QUIC is expected to fail.

This said the protocol shouldn't be announced in the first place.

**Comment by RubenKelevra** [comment]
While `QmZJznS5TWZiea2zdV63qJzYkz6P5HBhPksojxhrfNximP` is part of the cluster, it's not a node I run.

Try the import node odin:

`/ip6/2a03:4000:46:26e:b42e:2bff:fe07:c3fb/tcp/443/p2p/QmVoV4RiGLcxAfhA181GXR867bzVxmRTWwaubvhUyFrBwB`

**Comment by RubenKelevra** [comment]
You can put this peer into your list of persistent connections if you like: 

https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#peeringpeers

That said, you might want to look into pubsub/gossipsup to avoid having to look up the CIDs via the DHT.

**Comment by RubenKelevra** [comment]
Also: Your DHT connection might not work very well... reason being that you cannot reach any IPv4-only nodes, which are pretty common.

Not sure using a relay connection would help, but you can try:

https://github.com/ipfs/go-ipfs/blob/master/docs/config.md

**Comment by RubenKelevra** [comment]
I close this ticket due to inactivity. If there's still an issue with the latest IPFS version, please create a new one.
