### ISSUE TITLE
ipfs resolve fails

### ISSUE THREAD

**Issue by HeavyHorst** [RubenKelevra/pacman.store#52]
Since a few days I get, both on my laptops and on my server (that joined the cluster) the error: 
`ipfs resolve -r /ipns/cluster.pkg.pacman.store: could not resolve name`

**Comment by Luflosi** [comment]
Same problem here, I tried it from two different servers in two different networks.

**Comment by teknomunk** [comment]
I can confirm I am unable to resolve either cluster.pkg.pacman.store or pkg.pacman.store

**Comment by gileri** [comment]
Same from [ipfs.io](https://ipfs.io/ipns/x86-64.archlinux.pkg.pacman.store/).

**Comment by Luflosi** [comment]
This problem seems to be resolved, however the last update to any package is from the 17th of April. There are no new package updates.

**Comment by RubenKelevra** [comment]
Yeah IPFS hung up. Not sure why, I restarted it like 2-3 weeks ago as I noticed it.

I'm talking a look at it, what's wrong now and add a notification which covers it :)

**Comment by RubenKelevra** [comment]
Great, IPFS just hung on a file-add. I installed the latest version and it'll catch up with the official mirror soon.

**Comment by jcaesar** [comment]
Stacks up nicely with the new parallel downloads of pacman 6.
