### ISSUE TITLE
Import stuck again?

### ISSUE THREAD

**Issue by Luflosi** [RubenKelevra/pacman.store#53]
The import seems to have stopped again. lastsync is from 2021.06.12.
Does anyone else have this problem?

**Comment by RubenKelevra** [comment]
IPFS got stuck at:

`ipfs repo stat`


I use it to have a look at the space consumption which then either triggers the GC manually or not, depending on the result.

**Comment by RubenKelevra** [comment]
[I reported the issue](https://github.com/ipfs/go-ipfs/issues/8195) and [wrote a workaround](https://github.com/RubenKelevra/rsync2ipfs-cluster/commit/507cd06a6c6c34b89e7d3ca34cf3e72fee5b8d7a).

GC is currently running and then I'll start the import again.

**Comment by RubenKelevra** [comment]
I think I have to change something on the setup. The badgerds just won't work as performant as expected over a long time.

**Comment by RubenKelevra** [comment]
While my setup is now theoretically ready to go, I can't push new records to the ipns due to https://github.com/ipfs/go-ipfs/issues/6683. Great.

We have to wait 96 hours for the record to expire.

**Comment by RubenKelevra** [comment]
I rotated the key in the DNS record. So depending on your caching it should be fixed. TTL on the DNS record is just 900 seconds. So as long as all caches behave well it should be fixed for everyone.
