### ISSUE TITLE
Log spam "multicodec did not match"

### ISSUE THREAD

**Issue by Luflosi** [RubenKelevra/pacman.store#55]
When something is currently being pinned `ipfs-cluster-follow` spams my log with `ERROR        monitor        multicodec did not match` every few seconds.
Could this be a problem with my setup or with the cluster?

**Comment by RubenKelevra** [comment]
Hey @Luflosi,

neither your setup nor the cluster is the issue here (unless you forgot to update to 0.14).

The issue is incompatibility between version 0.13.x and 0.14.x in the communication protocol.

This is the upstream bug report about the logspam:

https://github.com/ipfs/ipfs-cluster/issues/1409

**Comment by Luflosi** [comment]
Thanks for the tip. Yes, I'm still running 0.13.1 as that is the current version of the package on NixOS. I use the GitHub watch functionality to watch for new releases but unfortunately there are only tags and they don't count as releases and so I don't get notified of new versions 😕.

**Comment by RubenKelevra** [comment]
> Thanks for the tip. Yes, I'm still running 0.13.1 as that is the current version of the package on NixOS. I use the GitHub watch functionality to watch for new releases but unfortunately there are only tags and they don't count as releases and so I don't get notified of new versions 😕.

Well, dist.ipfs.io has RSS :)

**Comment by hsanjuan** [comment]
> but unfortunately there are only tags and they don't count as releases and so I don't get notified of new versions

Ugh. I wish github was a bit more intelligent about annotated tags in the form of vX.Y.Z. I can try to click my way and make releases.
