### ISSUE TITLE
create a simple custom mount script for pacman.store, which mounts the latest version via ipfs-api-mount

### ISSUE THREAD

**Issue by RubenKelevra** [RubenKelevra/pacman.store#8]

**Comment by guysv** [comment]
Is the FUSE mount necessary? why not just using the local http gateway? pacman already speaks http.

**Comment by RubenKelevra** [comment]
@guysv no, I won't use the fuse mount. It's too slow and crashed on me a few times while testing.

There's a third party application I'll use which uses the API to requests the files and mount them much faster.

Using a local http gateway isn't a good solution either, you would copy the file from the ipfs to the harddrive, to read it again from the harddrive to send it via link local to pacman which stores it again on the harddrive.

This will not only use up twice the storage space on /var it would also cause a lot of unnecessary IO on the harddrive for /var and you still have a solution to clean up the pacman cache afterwards to get rid of old files in it.

Yeah sure you could run an IPFS add for those files in the pacman cache, but this would add another round of unnecessary IO for reading those files plus the CPU time to calculate the CID after which it's IPFS will realize that it already got that data and just drop it.

Using an additionally read only cache for pacman will reduce the IO and installation time to a minimum plus having the advantage that IPFS can garbage collect the pacman cache as needed.

**Comment by guysv** [comment]
Yes, I see your point.
